#!/usr/bin/env bash

set -e

function printInfo() {
    YELLOW='\033[0;33m'
    NC='\033[0m' # No Color

    echo -e "${YELLOW}$1${NC}"
}

# Install xcode
if [[ $(/usr/bin/gcc 2>&1) =~ "no developer tools were found" ]] || [[ ! -x /usr/bin/gcc ]]; then
    printInfo 'Installing XCode'
    xcode-select --install
fi

# Install homebrew
if [[ ! -x /usr/local/bin/brew ]]; then
    printInfo Installing Homebrew
    ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
fi

# Reconfigura Path
export PATH=/usr/local/bin:$PATH

# Install ansible
if [[ ! -x /usr/local/bin/ansible ]]; then
    printInfo Installing Ansible
    brew install ansible
fi

# Install git
if [[ ! -x /usr/local/bin/git ]]; then
    printInfo Installing Git
    brew install git
fi

# Clone this repository
macSetupDir=$HOME/.mac-setup
git clone https://github.com/fefas/mac-setup.git $macSetupDir
