#!/usr/bin/env bash

set -e

# Install xcode
if [[ $(/usr/bin/gcc 2>&1) =~ "no developer tools were found" ]] || [[ ! -x /usr/bin/gcc ]]; then
    printInfo Installing XCode
    xcode-select --install
fi

# Install homebrew
if [[ ! -x /usr/local/bin/brew ]]; then
    echo Installing Homebrew
    ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
fi

# Reconfigura Path
export PATH=/usr/local/bin:$PATH

# Install ansible
if [[ ! -x /usr/local/bin/ansible ]]; then
    echo Installing Ansible
    brew install ansible
fi

# Install git
if [[ ! -x /usr/local/bin/git ]]; then
    echo Installing Git
    brew install git
fi

# Clone this repository
macSetupDir=$HOME/Downloads/mac-setup
git clone https://github.com/fefas/mac-setup.git $macSetupDir

# Install desktop applications and CLI through ansible
cd $macSetupDir
ansible-playbook -i ansible/hosts.ini ansible/install.yml
