#!/usr/bin/env bash

WORK_DIR=$HOME/.mac-setup
SRC_DIR=$WORK_DIR/src
DOTFILES_DIR=$WORK_DIR/dotfiles

function printHelp() {
    echo "Use one of the following commands"
    echo "  init"
    echo "  install"
    echo "  update"

    exit 1
}

function runAnsible() {
    ANSIBLE_DIR=$SRC_DIR/ansible
    ansible-playbook -i $ANSIBLE_DIR/hosts.ini $ANSIBLE_DIR/$1.yaml
}

command=$1

case $command in
    "init") runAnsible init ;;
    "install") runAnsible install ;;
    "update") runAnsible update ;;
    *) printHelp
esac
