#!/usr/bin/env bash

export WORK_DIR=$HOME/.mac-setup
export SRC_DIR=$WORK_DIR/src
export DOTFILES_DIR=$WORK_DIR/dotfiles
export CONFIG_FILE=$DOTFILES_DIR/mac-setup.yaml
export CONFIG_CUSTOM_TASKS=$DOTFILES_DIR/mac-setup.custom-tasks.yaml

function printHelp() {
    echo "Use one of the following commands"
    echo "  init"
    echo "  install"
    echo "  update"

    exit 1
}

function runAnsible() {
    ANSIBLE_DIR=$SRC_DIR/ansible
    ansible-playbook -i $ANSIBLE_DIR/hosts.ini $ANSIBLE_DIR/$1.yaml
}

command=$1

case $command in
    "init") runAnsible init ;;
    "install") runAnsible install ;;
    "update") runAnsible update ;;
    *) printHelp
esac
