#!/usr/bin/env sh

set -e

usbDriveName='Fefas UsbDr'
usbDriveDir="/Volumes/$usbDriveName"

if [ ! -d "$usbDriveDir" ]; then
  echo Make sure $usbDriveName is pluged
  exit 1
fi

keysDir=$HOME/.ssh

mkdir -p $keysDir
cp "$usbDriveDir"/id_rsa* $keysDir

chmod 0600 $keysDir/id_rsa*
