#!/usr/bin/env sh

set -e

ohMyZshDir=$HOME/.oh-my-zsh
pluginHighlightDir=$ohMyZshDir/plugins/zsh-syntax-highlighting

if [ ! -d $ohMyZshDir ]; then
    bash -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
fi

if [ ! -d $pluginHighlightDir ]; then
    git clone https://github.com/zsh-users/zsh-syntax-highlighting.git $pluginHighlightDir
fi
