---
- hosts: localhost

  tasks:
    - name: Configure dotfiles
      file:
        src: /Users/fefas/Dropbox/Coding/{{ item.src }}
        dest: $HOME/{{ item.dest }}
        state: link
      with_items:
        - src: fefas/dotfiles/vimrc
          dest: .vimrc
        - src: fefas/dotfiles/gitignore
          dest: .gitignore_global
        - src: fefas/dotfiles/gitconfig
          dest: .gitconfig
        - src: fefas/dotfiles/zshrc
          dest: .zshrc

    - name: Install vim plugins
      command: vim +qall
