---
- hosts: localhost

  vars_prompt:
  - name: username
    prompt: "Enter a github user name for cloning dotfiles"
    private: no

  tasks:
  - name: Clone dotfiles
    git:
      repo: 'git@github.com:{{ username }}/dotfiles.git'
      dest: '{{ ansible_env.DOTFILES_DIR }}'
      version: master
