---
- hosts: localhost

  tasks:
    - name: Update homebrew
      homebrew:
        update_homebrew: yes

    - name: Install desktop applications
      homebrew_cask: name={{ item }}
      with_items:
        - sequel-pro
        - todoist
        - 1password
        - dropbox
        - google-chrome
        - firefox
        - iterm2
        - atom
        - phpstorm
        - docker
        - ngrok
        - gimp
        - slack
        - telegram
        - whatsapp
        - rescuetime
        - steam
        - spotify

    - name: Install CLI tools
      homebrew: name={{ item.name }}
      with_items:
        - name: openssh
        - name: vim
        - name: tmux
        - name: watch
        - name: zsh
        - name: cmake
        - name: gcc
        - name: ruby
        - name: php@7.4
        - name: composer
        - name: node
        - name: wget
        - name: curl
        - name: jq
        - name: git
        - name: git-quick-stats
        - name: tree
        - name: docker
        - name: docker-compose
        - name: docker-machine

    - name: Install oh-my-zsh
      script: ./custom-scripts/install-oh-my-zsh
