---
- hosts: localhost
  vars:
    workDir: ~/.mac-setup
    srcDir: '{{ workDir }}/src'
    dotfilesDir: '{{ workDir }}/dotfiles'

  tasks:
  - name: Link dotfiles
    file:
      state: link
      src: '{{ dotfilesDir }}/{{ item.src }}'
      dest: '~/{{ item.dest }}'
      force: yes
    with_items:
    - src: gitconfig
      dest: .gitconfig
    - src: gitignore
      dest: .gitignore_global
    - src: tmux.conf
      dest: .tmux.conf
    - src: vimrc
      dest: .vimrc
    - src: zshrc
      dest: .zshrc

  - name: Install desktop applications
    homebrew_cask: name={{ item }}
    with_items:
    - 1password
    # - atom
    - docker
    - dropbox
    - firefox
    - gimp
    - google-chrome
    - iterm2
    - phpstorm
    - rescuetime
    - slack
    # - spotify
    - steam
    - telegram
    - whatsapp

  - name: Install CLI tools
    homebrew: name={{ item.name }}
    with_items:
    - name: cmake
    - name: composer
    - name: curl
    - name: docker
    - name: docker-compose
    - name: docker-machine
    - name: gcc
    - name: git
    - name: jq
    - name: openssh
    - name: node
    - name: php@7.4
    - name: python3
    - name: ruby
    - name: tmux
    - name: tree
    - name: vim
    - name: watch
    - name: wget
    - name: zsh

  - name: Install oh-my-zsh
    script: ./custom-scripts/install-oh-my-zsh
