---
- hosts: localhost

  tasks:
    - name: Homebrew tap PHP
      homebrew_tap:
        name: homebrew/php

    - name: Update homebrew
      homebrew:
        update_homebrew: yes

    - name: Install desktop applications
      homebrew_cask: name={{ item }}
      with_items:
        - 1password
        - dropbox
        - google-chrome
        - iterm2
        - atom
        - caskroom/cask/intellij-idea-ce
        - java
        - docker
        - vagrant
        - virtualbox
        - ngrok
        - gimp
        - slack
        - skype
        - telegram
        - icq
        - whatsapp
        - rescuetime
        - steam
        - spotify
        - lastfm
        - android-file-transfer

    - name: Install CLI tools
      homebrew: name={{ item.name }}
      with_items:
        - name: openssh
        - name: vim
        - name: macvim
        - name: tmux
        - name: zsh
        - name: cmake
        - name: gcc
        - name: ruby
        - name: sbt@1
        - name: php72
        - name: composer
        - name: node
        - name: mysql
        - name: wget
        - name: curl
        - name: jq
        - name: git
        - name: git-quick-stats
        - name: tree
        - name: docker
        - name: docker-compose
        - name: docker-machine

    - name: Install oh-my-zsh
      script: ./custom-scripts/install-oh-my-zsh
