---
- hosts: localhost

  tasks:
  - name: Check config file
    stat:
      path: '{{ ansible_env.CONFIG_FILE }}'
    register: configFileResult

  - name: Check custom tasks file
    stat:
      path: '{{ ansible_env.CONFIG_CUSTOM_TASKS }}'
    register: customTasks

  - name: Abort if config file does not exist
    fail:
      msg: "Please, create a proper config file '{{ ansible_env.CONFIG_FILE }}'"
    when: not configFileResult.stat.exists

  - name: Include config file
    include_vars:
      file: '{{ ansible_env.CONFIG_FILE }}'
      name: config

  - name: Link dotfiles
    file:
      state: link
      src: '{{ ansible_env.DOTFILES_DIR }}/{{ item.src }}'
      dest: '{{ ansible_env.HOME }}/{{ item.dest }}'
      force: yes
    with_items: '{{ config.dotfiles }}'

  - name: Install desktop applications
    homebrew_cask: name={{ item }}
    with_items: '{{ config.brewCask }}'

  - name: Install CLI tools
    homebrew: name={{ item.name }}
    with_items: '{{ config.brew }}'

  - name: Custom tasks
    include_tasks: '{{ customTasks.stat.path }}'
    when: customTasks.stat.exists

  #- name: Install oh-my-zsh
  #  script: ./custom-scripts/install-oh-my-zsh
