---
- hosts: localhost

  tasks:
    - name: Homebrew tap PHP
      homebrew_tap:
        name: homebrew/php

    - name: Update homebrew
      homebrew:
        update_homebrew: yes

    - name: Install desktop applications
      homebrew_cask: name={{ item }}
      with_items:
        - 1password
        - dropbox
        - google-chrome
        - iterm2
        - docker
        - vagrant
        - virtualbox
        - atom
        - gimp
        - slack
        - skype
        - telegram
        - whatsapp
        - rescuetime
        - android-file-transfer
        - steam
        - lastfm

    - name: Install CLI tools
      homebrew: name={{ item.name }}
      with_items:
        - name: openssh
        - name: vim
        - name: tmux
        - name: zsh
        - name: cmake
        - name: gcc
        - name: ruby
        - name: php72
        - name: composer
        - name: node
        - name: wget
        - name: curl
        - name: jq
        - name: git
        - name: tree
        - name: docker
        - name: docker-compose
        - name: docker-machine

    - name: Install oh-my-zsh
      script: ./custom-scripts/install-oh-my-zsh

    - gem:
        name: travis
        version: 1.8.8
        build_flags: --no-rdoc --no-ri
        user_install: no
