---
- hosts: localhost

  tasks:
    - name: Update homebrew
      homebrew:
        update_homebrew: yes

    - name: Install desktop applications
      homebrew_cask: name={{ item }}
      with_items:
        - 1password
        - dropbox
        - google-chrome
        - iterm2
        - atom
        - sourcetree
        - gimp
        - slack
        - skype
        - telegram
        - whatsapp
        - rescuetime
        - android-file-transfer

    - name: Install CLI tools
      homebrew: name={{ item.name }}
      with_items:
        - name: vim
        - name: tmux
        - name: git
        - name: tree
        - name: jq
