---
- hosts: localhost

  tasks:
  - name: Determine mac-setup repo
    shell:
      cmd: git config --get remote.origin.url
      chdir: '{{ ansible_env.SRC_DIR }}'
    register: selfRepoCmd

  - name: Determine dotfiles repo
    shell:
      cmd: git config --get remote.origin.url
      chdir: '{{ ansible_env.DOTFILES_DIR }}'
    register: dotfilesRepoCmd

  - name: Update mac-setup
    git:
      repo: "{{ selfRepoCmd.stdout }}"
      dest: "{{ ansible_env.SRC_DIR }}"
      update: yes

  - name: Update dotfiles
    git:
      repo: "{{ dotfilesRepoCmd.stdout }}"
      dest: "{{ ansible_env.DOTFILES_DIR }}"
      update: yes
      version: master

  - name: Update homebrew
    homebrew:
      update_homebrew: yes
      upgrade_all: yes
